"""
response_parser.py
==================

Parses raw LLM responses into structured review objects.

Responsibilities
----------------
* Parse AI-generated code review responses.
* Extract structured review sections.
* Handle missing sections gracefully.
* Produce consistent output for downstream modules.
"""

from __future__ import annotations

###############################################################################
# Standard Library Imports
###############################################################################

import re
from dataclasses import dataclass, field
from typing import Dict, List

###############################################################################
# Section Headings
###############################################################################

SECTION_HEADERS = {
    "summary": "## Overall Summary",
    "strengths": "## Strengths",
    "issues": "## Issues",
    "security": "## Security",
    "performance": "## Performance",
    "maintainability": "## Maintainability",
    "improvements": "## Suggested Improvements",
    "improved_code": "## Improved Code",
    "verdict": "## Final Verdict",
}

###############################################################################
# Parsed Review
###############################################################################


@dataclass(slots=True)
class ParsedReview:
    """
    Structured representation of a code review.
    """

    summary: str = ""

    strengths: List[str] = field(
        default_factory=list
    )

    issues: List[str] = field(
        default_factory=list
    )

    security: List[str] = field(
        default_factory=list
    )

    performance: List[str] = field(
        default_factory=list
    )

    maintainability: List[str] = field(
        default_factory=list
    )

    improvements: List[str] = field(
        default_factory=list
    )

    improved_code: str = ""

    verdict: str = ""

    raw_response: str = ""

    ###########################################################################

    @property
    def issue_count(
        self,
    ) -> int:

        return len(self.issues)

    ###########################################################################

    @property
    def has_security_issues(
        self,
    ) -> bool:

        return len(self.security) > 0

    ###########################################################################

    @property
    def is_clean(
        self,
    ) -> bool:

        return (
            self.issue_count == 0
            and not self.security
        )

    ###########################################################################

    def to_dict(
        self,
    ) -> Dict:

        return {
            "summary": self.summary,
            "strengths": self.strengths,
            "issues": self.issues,
            "security": self.security,
            "performance": self.performance,
            "maintainability": self.maintainability,
            "improvements": self.improvements,
            "improved_code": self.improved_code,
            "verdict": self.verdict,
            "raw_response": self.raw_response,
        }

###############################################################################
# Response Parser
###############################################################################


class ReviewResponseParser:
    """
    Parses markdown responses generated by the LLM.
    """

    ###########################################################################

    @staticmethod
    def _parse_code_block(
        section: str,
    ) -> str:
        """
        Extract improved code from a section. Strips a single
        surrounding markdown code fence if present. Treats a bare
        "None." (the model explicitly declining to provide improved
        code) as empty.
        """

        text = section.strip()

        if not text or text.rstrip(".").strip().lower() == "none":
            return ""

        fence_match = re.search(
            r"```[a-zA-Z0-9_+-]*\n(.*?)```",
            text,
            flags=re.DOTALL,
        )

        if fence_match:
            return fence_match.group(1).strip()

        return text

    ###########################################################################

    @staticmethod
    def _extract_section(
        text: str,
        header: str,
        next_headers: List[str],
    ) -> str:
        """
        Extract a markdown section.
        """

        pattern = (
            re.escape(header)
            + r"(.*?)"
        )

        # Always include an end-of-string alternative, not just when
        # next_headers is non-empty. Without this, the last header in
        # sequence (## Final Verdict) had no terminating lookahead at
        # all, and a lazy `.*?` with nothing to anchor against always
        # matches zero characters - silently returning "" for the
        # final section on every single response.
        alternatives = [
            re.escape(h)
            for h in next_headers
        ] + [r"$"]

        pattern += (
            "(?="
            + "|".join(alternatives)
            + ")"
        )

        match = re.search(
            pattern,
            text,
            flags=re.DOTALL,
        )

        if not match:

            return ""

        return match.group(1).strip()

    ###########################################################################

    @staticmethod
    def _parse_list(
        section: str,
    ) -> List[str]:
        """
        Convert markdown bullets into a list.
        """

        items = []

        for line in section.splitlines():

            line = line.strip()

            if not line:

                continue

            if line.startswith("-"):

                items.append(
                    line[1:].strip()
                )

            elif line.startswith("*"):

                items.append(
                    line[1:].strip()
                )

        return items

    ###########################################################################

    def parse(
        self,
        response: str,
    ) -> ParsedReview:
        """
        Parse an LLM response.
        """

        review = ParsedReview(
            raw_response=response
        )

        headers = list(
            SECTION_HEADERS.values()
        )

        extracted = {}

        for index, header in enumerate(headers):

            remaining = headers[index + 1:]

            extracted[header] = self._extract_section(
                response,
                header,
                remaining,
            )

        review.summary = extracted[
            SECTION_HEADERS["summary"]
        ]

        review.strengths = self._parse_list(
            extracted[
                SECTION_HEADERS["strengths"]
            ]
        )

        review.issues = self._parse_list(
            extracted[
                SECTION_HEADERS["issues"]
            ]
        )

        review.security = self._parse_list(
            extracted[
                SECTION_HEADERS["security"]
            ]
        )

        review.performance = self._parse_list(
            extracted[
                SECTION_HEADERS["performance"]
            ]
        )

        review.maintainability = self._parse_list(
            extracted[
                SECTION_HEADERS["maintainability"]
            ]
        )

        review.improvements = self._parse_list(
            extracted[
                SECTION_HEADERS["improvements"]
            ]
        )

        review.improved_code = self._parse_code_block(
            extracted[
                SECTION_HEADERS["improved_code"]
            ]
        )

        review.verdict = extracted[
            SECTION_HEADERS["verdict"]
        ]
        return review

    ###########################################################################

    def validate(
        self,
        review: ParsedReview,
    ) -> bool:
        """
        Validate that the parsed review contains
        the minimum required sections.
        """

        return bool(
            review.summary.strip()
            and review.verdict.strip()
        )

    ###########################################################################

    def statistics(
        self,
        review: ParsedReview,
    ) -> Dict[str, int]:
        """
        Return statistics about the parsed review.
        """

        return {
            "strengths": len(review.strengths),
            "issues": len(review.issues),
            "security_findings": len(review.security),
            "performance_findings": len(review.performance),
            "maintainability_findings": len(
                review.maintainability
            ),
            "improvements": len(
                review.improvements
            ),
            "total_findings": (
                len(review.issues)
                + len(review.security)
                + len(review.performance)
                + len(review.maintainability)
            ),
        }

    ###########################################################################

    def to_markdown(
        self,
        review: ParsedReview,
    ) -> str:
        """
        Convert ParsedReview back to markdown.
        """

        def bullets(items: List[str]) -> str:

            if not items:
                return "- None"

            return "\n".join(
                f"- {item}"
                for item in items
            )

        return f"""## Overall Summary

{review.summary}

## Strengths

{bullets(review.strengths)}

## Issues

{bullets(review.issues)}

## Security

{bullets(review.security)}

## Performance

{bullets(review.performance)}

## Maintainability

{bullets(review.maintainability)}

## Suggested Improvements

{bullets(review.improvements)}

## Final Verdict

{review.verdict}
"""

    ###########################################################################

    def to_json(
        self,
        review: ParsedReview,
    ) -> Dict:
        """
        Convert ParsedReview to JSON-compatible
        dictionary.
        """

        return review.to_dict()

    ###########################################################################

    def info(
        self,
    ) -> Dict[str, str]:
        """
        Return parser information.
        """

        return {
            "parser": self.__class__.__name__,
            "supported_format": "Markdown",
        }

    ###########################################################################

    def __repr__(
        self,
    ) -> str:

        return (
            f"{self.__class__.__name__}("
            "markdown_parser=True)"
        )


###############################################################################
# Convenience Function
###############################################################################


def parse_review(
    response: str,
) -> ParsedReview:
    """
    Parse an LLM review response using the default parser.
    """

    parser = ReviewResponseParser()

    return parser.parse(response)


###############################################################################
# CLI Example
###############################################################################

if __name__ == "__main__":

    sample_response = """
## Overall Summary

The implementation is generally good but has a few issues.

## Strengths

- Clean function decomposition
- Good variable names

## Issues

- Missing input validation
- Division by zero is possible

## Security

- No input sanitization

## Performance

- Nested loop can be optimized

## Maintainability

- Duplicate logic detected

## Suggested Improvements

- Add exception handling
- Refactor repeated code

## Final Verdict

Good implementation with minor improvements required.
"""

    parser = ReviewResponseParser()

    review = parser.parse(
        sample_response
    )

    print("=" * 80)
    print("Parser Information")
    print("=" * 80)
    print(parser.info())

    print("\nStatistics")
    print("=" * 80)
    print(
        parser.statistics(review)
    )

    print("\nIs Valid Review?")
    print("=" * 80)
    print(
        parser.validate(review)
    )

    print("\nMarkdown Output")
    print("=" * 80)
    print(
        parser.to_markdown(review)
    )


###############################################################################
# Public Exports
###############################################################################

__all__ = [
    "SECTION_HEADERS",
    "ParsedReview",
    "ReviewResponseParser",
    "parse_review",
]